[package]
name = "rust_ltspice_parser"
version = "0.1.0"
authors = ["Daniel Thiem <info@daniel-thiem.de>"]

[lib]
name = "ltspice_parse"
path = "src/lib.rs"

[[bin]]
name = "ltspice_run"
path = "src/main.rs"

[dependencies]
byteorder = "0.4.2"
num = "0.1"
gnuplot = "0.0.20"
statistical = "0.1.1"
